### ISSUE TITLE
As a user, I want to mark a todo done

### ISSUE THREAD

**Issue by boszormenyip** [boszormenyip/jgtd#18]
The todo is only shown in the done list

**Comment by 0pdd** [comment]
@boszormenyip the puzzle [#26](https://github.com/boszormenyip/jgtd/issues/26) is still not solved.

**Comment by 0pdd** [comment]
@boszormenyip the only puzzle [#26](https://github.com/boszormenyip/jgtd/issues/26) is solved here.
