### ISSUE TITLE
Break apart MainScreenPresenter 

### ISSUE THREAD

**Issue by boszormenyip** [boszormenyip/jgtd#44]
The presenter is too big, it has to be separated into smaller presenters, which responsible only part of the screen.

**Comment by 0pdd** [comment]
@boszormenyip 2 puzzles [#48](https://github.com/boszormenyip/jgtd/issues/48), [#49](https://github.com/boszormenyip/jgtd/issues/49) are still not solved.

**Comment by 0pdd** [comment]
@boszormenyip the puzzle [#49](https://github.com/boszormenyip/jgtd/issues/49) is still not solved; solved: [#48](https://github.com/boszormenyip/jgtd/issues/48).

**Comment by 0pdd** [comment]
@boszormenyip all 2 puzzles are solved here: [#48](https://github.com/boszormenyip/jgtd/issues/48), [#49](https://github.com/boszormenyip/jgtd/issues/49).
