### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by boszormenyip** [boszormenyip/jgtd#6]
There are several problematic, the design not yet clear type code. It has to be cleaned up.

**Comment by 0pdd** [comment]
@boszormenyip 10 puzzles [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#16](https://github.com/boszormenyip/jgtd/issues/16), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#8](https://github.com/boszormenyip/jgtd/issues/8), [#9](https://github.com/boszormenyip/jgtd/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@boszormenyip 13 puzzles [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#16](https://github.com/boszormenyip/jgtd/issues/16), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#8](https://github.com/boszormenyip/jgtd/issues/8) are still not solved; solved: [#17](https://github.com/boszormenyip/jgtd/issues/17), [#9](https://github.com/boszormenyip/jgtd/issues/9).

**Comment by 0pdd** [comment]
@boszormenyip 13 puzzles [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#16](https://github.com/boszormenyip/jgtd/issues/16), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#29](https://github.com/boszormenyip/jgtd/issues/29), [#31](https://github.com/boszormenyip/jgtd/issues/31), [#8](https://github.com/boszormenyip/jgtd/issues/8) are still not solved; solved: [#12](https://github.com/boszormenyip/jgtd/issues/12), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#9](https://github.com/boszormenyip/jgtd/issues/9).

**Comment by 0pdd** [comment]
@boszormenyip 9 puzzles [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#16](https://github.com/boszormenyip/jgtd/issues/16), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#29](https://github.com/boszormenyip/jgtd/issues/29), [#31](https://github.com/boszormenyip/jgtd/issues/31), [#34](https://github.com/boszormenyip/jgtd/issues/34) are still not solved; solved: [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#8](https://github.com/boszormenyip/jgtd/issues/8), [#9](https://github.com/boszormenyip/jgtd/issues/9).

**Comment by 0pdd** [comment]
@boszormenyip 14 puzzles [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#16](https://github.com/boszormenyip/jgtd/issues/16), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#29](https://github.com/boszormenyip/jgtd/issues/29), [#31](https://github.com/boszormenyip/jgtd/issues/31), [#34](https://github.com/boszormenyip/jgtd/issues/34), [#37](https://github.com/boszormenyip/jgtd/issues/37), [#39](https://github.com/boszormenyip/jgtd/issues/39), [#40](https://github.com/boszormenyip/jgtd/issues/40), [#41](https://github.com/boszormenyip/jgtd/issues/41), [#42](https://github.com/boszormenyip/jgtd/issues/42) are still not solved; solved: [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#8](https://github.com/boszormenyip/jgtd/issues/8), [#9](https://github.com/boszormenyip/jgtd/issues/9).

**Comment by 0pdd** [comment]
@boszormenyip 3 puzzles [#16](https://github.com/boszormenyip/jgtd/issues/16), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#45](https://github.com/boszormenyip/jgtd/issues/45) are still not solved; solved: [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#29](https://github.com/boszormenyip/jgtd/issues/29), [#31](https://github.com/boszormenyip/jgtd/issues/31), [#34](https://github.com/boszormenyip/jgtd/issues/34), [#37](https://github.com/boszormenyip/jgtd/issues/37), [#39](https://github.com/boszormenyip/jgtd/issues/39), [#40](https://github.com/boszormenyip/jgtd/issues/40), [#41](https://github.com/boszormenyip/jgtd/issues/41), [#42](https://github.com/boszormenyip/jgtd/issues/42), [#8](https://github.com/boszormenyip/jgtd/issues/8), [#9](https://github.com/boszormenyip/jgtd/issues/9).

**Comment by 0pdd** [comment]
@boszormenyip 2 puzzles [#16](https://github.com/boszormenyip/jgtd/issues/16), [#45](https://github.com/boszormenyip/jgtd/issues/45) are still not solved; solved: [#10](https://github.com/boszormenyip/jgtd/issues/10), [#11](https://github.com/boszormenyip/jgtd/issues/11), [#12](https://github.com/boszormenyip/jgtd/issues/12), [#13](https://github.com/boszormenyip/jgtd/issues/13), [#14](https://github.com/boszormenyip/jgtd/issues/14), [#15](https://github.com/boszormenyip/jgtd/issues/15), [#17](https://github.com/boszormenyip/jgtd/issues/17), [#21](https://github.com/boszormenyip/jgtd/issues/21), [#22](https://github.com/boszormenyip/jgtd/issues/22), [#23](https://github.com/boszormenyip/jgtd/issues/23), [#24](https://github.com/boszormenyip/jgtd/issues/24), [#25](https://github.com/boszormenyip/jgtd/issues/25), [#29](https://github.com/boszormenyip/jgtd/issues/29), [#31](https://github.com/boszormenyip/jgtd/issues/31), [#34](https://github.com/boszormenyip/jgtd/issues/34), [#37](https://github.com/boszormenyip/jgtd/issues/37), [#39](https://github.com/boszormenyip/jgtd/issues/39), [#40](https://github.com/boszormenyip/jgtd/issues/40), [#41](https://github.com/boszormenyip/jgtd/issues/41), [#42](https://github.com/boszormenyip/jgtd/issues/42), [#8](https://github.com/boszormenyip/jgtd/issues/8), [#9](https://github.com/boszormenyip/jgtd/issues/9).
